version: '3.1'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

volumes:
  pgdata: